First PR
oerkperl/crypto-app pull request #1
Opened 2024-01-14 12:19 UTC by oerkperl

The home chart for bitcoin.

2024-01-15 14:55 UTC, yoloOnTheBattlefield requested changes
https://www.loom.com/share/d22c5fafab3440768f0313a46ee2e187?from_recorder=1&focus_title=1

2024-01-15 14:55 UTC, yoloOnTheBattlefield commented on app/components/home/charts/Charts.tsx
> +        console.log(data.prices);
remove

2024-01-15 14:55 UTC, yoloOnTheBattlefield commented on app/components/styled.ts
> +padding:0 .5rem;
indent

2024-01-15 14:55 UTC, yoloOnTheBattlefield commented on app/components/styled.ts
> +color:#888
indent

2024-01-26 08:46 UTC, oerkperl commented on app/components/styled.ts
> +color:#888
Addressed.

2024-01-29 14:07 UTC, merged