more styling ref
oerkperl/crypto-app pull request #21
Opened 2024-04-04 17:55 UTC by oerkperl

2024-04-04 19:42 UTC, yoloOnTheBattlefield requested changes

2024-04-04 19:42 UTC, yoloOnTheBattlefield commented on app/components/coin/LinksList.tsx
> +// };
delete these lines

2024-04-04 19:42 UTC, yoloOnTheBattlefield commented on app/components/coin/LinksList.tsx
> +            links.map((link) =>
filter before you map

2024-04-04 19:42 UTC, yoloOnTheBattlefield commented on app/components/portfolio/MyAsset.tsx
> +              }}
no need for curly brackets here

2024-04-05 10:30 UTC, oerkperl reviewed
sorted.

2024-04-05 10:31 UTC, merged